### ISSUE TITLE
Initialize Amplitude for comprehensive tracking of user interactions

### ISSUE THREAD

**Issue by Taegon21** [BLink-Org/BLink-client#37]
## 📂 구현 기능

Amplitude를 사용자 ID와 함께 초기화하고 로그인, 로그아웃, 테마 설정 이벤트를 추적

## 📝 상세 작업 내용

- [x] 앱 진입 이벤트를 Amplitude에서 추적
- [x] 로그인 시, Amplitude에 사용자 ID를 전달하여 초기화
- [x] 로그인 이벤트, 로그아웃 이벤트를 추적 
- [x] 테마 설정 변경 이벤트를 Amplitude에서 추적
